extends SceneTree
const Game=preload("res://scripts/hero_campaign.gd")
const Motion=preload("res://scripts/pocket_motion.gd")
const Main=preload("res://scripts/pocket_main.gd")
var checks=0
var failures=0
func check(ok: bool,label: String):
 checks+=1
 if not ok: failures+=1;push_error("FAIL: "+label)
func count_kind(m,kind): return m.effects.filter(func(fx):return fx.kind==kind).size()
func _init(): call_deferred("run")
func run():
 if "--pocket-demo" not in OS.get_cmdline_user_args(): quit(1);return
 var g=Game.new();g.begin(0);var before=g.battle.duplicate(true);var saved_before=before.duplicate(true)
 g.play("rowan","cleave","enemy_1");var result=g.snapshot();var m=Motion.new()
 m.build(before,g.battle,"rowan","cleave")
 check(count_kind(m,"damage")==2 and count_kind(m,"slash")==2,"cleave animates every actual victim")
 check(count_kind(m,"vanish")==2,"defeated targets persist as brief ghosts")
 var ghosts=m.effects.filter(func(fx):return fx.kind=="vanish")
 check(ghosts[0].at==Vector2(292,310) and ghosts[1].at==Vector2(408,310),"dead targets keep distinct original positions in the new front")
 check(before==saved_before and g.snapshot()==result,"timeline never mutates either rules snapshot")
 m.advance(0.15);check(m.impact("enemy_1")>0 and m.offset("rowan").length()>0,"hit and attack motion evolve")
 m.advance(1);check(not m.active(),"all effects expire")
 g=Game.new();g.begin(0);before=g.battle.duplicate(true);g.play("lysa","volley","enemy_1")
 m.build(before,g.battle,"lysa","volley")
 check(count_kind(m,"arrow")==1,"Volley has a projectile")
 var successor=g.foe("enemy_4");var destination=Motion.point(successor,true,g.battle)
 check(m.position(successor.id,destination)==Vector2(408,310),"survivor starts at original slot")
 m.advance(0.2);check(m.position(successor.id,destination)==Vector2(408,310) and m.impact("enemy_1")==0,"formation and impact wait for arrow arrival")
 m.advance(0.47);check(m.position(successor.id,destination)==destination,"formation slides after defeated target fades")
 g=Game.new();g.campaign.xp=140;g.campaign.mage=true;g.campaign.items.staff=0;g.campaign.items.flask=0
 g.place("staff",4,2,0);g.place("flask",0,3,0);g.campaign.mastery={"rowan":2,"merrin":2};g.begin(0)
 g.foe("enemy_1").hp=40;g.foe("enemy_1").max_hp=40
 before=g.battle.duplicate(true);g.play("merrin","spark","enemy_1");m.build(before,g.battle,"merrin","spark")
 check(count_kind(m,"spell")==1 and count_kind(m,"stun")==1,"Storm displays spell and newly applied stun")
 g.resolve();g.ally("lysa").hp-=8;before=g.battle.duplicate(true);g.play("merrin","mend","lysa");m.build(before,g.battle,"merrin","mend")
 check(count_kind(m,"heal")==1 and count_kind(m,"shield")==1,"Heal includes actual healing and mastery block")
 check(count_kind(m,"slash")==0 and count_kind(m,"arrow")==0,"healing is not an attack trail")
 before=g.battle.duplicate(true);g.reposition("rowan",2);m.build(before,g.battle,"rowan","move")
 check(m.tracks.rowan.from!=m.tracks.rowan.to,"reposition tracks old and new fronts")
 m.advance(0.1);var middle=m.position("rowan",m.tracks.rowan.to)
 check(middle!=m.tracks.rowan.from and middle!=m.tracks.rowan.to,"movement has an intermediate frame")
 before=g.battle.duplicate(true);g.play("rowan","guard","rowan");m.build(before,g.battle,"rowan","guard")
 check(m.position("rowan",m.tracks.rowan.to)==middle,"rapid Guard preserves ongoing movement position")
 check(count_kind(m,"shield")==2,"Guard feedback includes shared mastery block")
 g=Game.new();g.begin(0);g.foe("enemy_1").stunned=true;before=g.battle.duplicate(true);g.resolve();m.build(before,g.battle,"","",true)
 check(count_kind(m,"skip")==1 and count_kind(m,"enemy")==4,"enemy turn differentiates skipped and active attacks")
 check(count_kind(m,"arrival")==3,"reinforcement wave receives arrival effects")
 g=Game.new();g.begin(0);g.play("rowan","guard","rowan");before=g.battle.duplicate(true)
 for e in before.enemies: e.motion_power=g.attack_power(e)
 g.resolve();m.build(before,g.battle,"","",true)
 check(m.summary.contains("Rowan blocked") and count_kind(m,"shield")>0,"absorbed hits have exact block feedback")
 g=Game.new();g.begin(0);g.ally("rowan").hp=1;before=g.battle.duplicate(true)
 for e in before.enemies: e.motion_power=g.attack_power(e)
 g.resolve();m.build(before,g.battle,"","",true)
 check(count_kind(m,"enemy")==4,"fixed-target attacks skipped after death do not animate")
 for i in range(100): m.build(before,g.battle,"","",true)
 check(m.effects.size()<40,"rapid updates replace rather than accumulate timelines")
 var screen=Main.new();root.add_child(screen);screen.muted=true;screen.game.begin(0);screen.page="battle";screen.show_page()
 screen.choose_card("cleave");screen.on_actor("enemy_1")
 check(screen.field.motion.active(),"native command connects animation timeline")
 var pending=screen.field.motion.effects.duplicate(true)
 screen.choose_card("strike");screen.on_actor("lysa")
 check(screen.field.motion.effects==pending,"invalid target creates no false effects")
 screen.undo_action();check(not screen.field.motion.active() and screen.game.foe("enemy_1").hp==10,"undo clears ghost effects and restores state")
 screen.reduced_motion=true;screen.show_page();screen.choose_card("cleave");screen.on_actor("enemy_1")
 check(not screen.field.motion.active(),"reduced motion gives immediate static result")
 check(screen.game.message.contains("HP"),"reduced motion retains stationary outcome detail")
 screen.reduced_motion=false;screen.show_page();screen.select_hero("lysa");screen.choose_card("volley");screen.on_actor("enemy_2")
 check(screen.field.motion.active(),"motion resumes when enabled")
 screen.reduced_motion=true;screen.show_page();check(not screen.field.motion.active(),"mid-flight reduced motion cancels spatial effects")
 screen.reduced_motion=false;screen.show_page()
 screen.select_hero("rowan");screen.move_to(2);screen.field.motion.advance(0.1);screen._process(0)
 var moving_control=screen.actor_controls.filter(func(entry):return entry.unit.id=="rowan")[0]
 check(moving_control.button.position==screen.field.unit_rect(screen.game.ally("rowan"),false).position,"native target follows rendered movement")
 screen.navigate("guide");check(not screen.field.motion.active(),"navigation clears stale effects")
 screen.navigate("battle");screen.game.battle.round=4;screen.resolve_turn()
 check(screen.finishing_impact and screen.game.battle.rewarded,"reward saved before presentation delay")
 var reward=screen.game.campaign.gold;screen.resolve_turn()
 check(not screen.finishing_impact and screen.game.campaign.gold==reward,"continue skips animation without duplicate reward")
 screen.game.begin(0);screen.game.battle.round=4;screen.resolve_turn();screen.navigate("guide")
 await create_timer(0.7).timeout
 check(screen.page=="guide" and not screen.finishing_impact,"navigation cancels delayed reward callback")
 screen.game.new_campaign();screen.game.begin(0);screen.page="battle";screen.coaching=false;screen.show_page()
 screen.choose_card("guard");screen.resolve_turn()
 var aftermath=screen.battle_notice
 check(aftermath.contains("Enemy turn") and aftermath.contains("blocked"),"Enemy turn leaves an inspectable exact damage/block summary")
 await create_timer(0.75).timeout
 check(not screen.field.motion.active() and screen.inspection.text==aftermath,"Outcome feedback remains after the animation expires")
 screen.select_hero("lysa")
 check(screen.battle_notice=="" and screen.inspection.text==screen.default_detail(),"Next selection clears old aftermath for the new decision")
 screen.queue_free();await process_frame;await process_frame
 print("MOTION TESTS: %d checks, %d failures" % [checks,failures])
 quit(1 if failures else 0)
